spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:bankdb}
    username: ${DB_USER:bankuser}
    password: ${DB_PASSWORD:bankpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  liquibase:
    change-log: classpath:db/migration/changelog-master.yml

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET:change_this_to_a_long_secret_key}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}
    issuer: bank-rest

springdoc:
  api-docs:
    path: D:/bank_rest/docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
